/**
 * Mock Data Service
 * 
 * This file contains mock data for development and testing purposes.
 * It provides realistic data that mimics what would be returned from the API.
 */

import { Asset, AssetStatistics, Inspection, ActivityItem, InspectionItem } from '@/types';

// Mock Assets
export const mockAssets: Asset[] = [
  {
    id: "1",
    name: "Forklift #A102",
    description: "Standard warehouse forklift with 5000lb capacity",
    serialNumber: "FL-5000-102",
    model: "FL5000",
    manufacturer: "Heavy Lifters Inc",
    category: "machinery",
    purchaseDate: "2020-03-15",
    purchasePrice: 25000,
    location: "Warehouse A",
    department: "Logistics",
    status: "active",
    lastInspection: "2023-04-15",
    nextInspection: "2023-05-15",
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=300&h=200",
    notes: "Regular maintenance required every 3 months",
  },
  {
    id: "2",
    name: "Air Compressor #C55",
    description: "Industrial air compressor for pneumatic tools",
    serialNumber: "AC-2000-55",
    model: "AC2000",
    manufacturer: "Pressure Pro",
    category: "machinery",
    purchaseDate: "2021-01-10",
    purchasePrice: 12000,
    location: "Workshop B",
    department: "Maintenance",
    status: "maintenance",
    lastInspection: "2023-03-20",
    nextInspection: "2023-06-20",
    image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=300&h=200",
    notes: "Needs filter replacement",
  },
  {
    id: "3",
    name: "Generator #G20",
    description: "Diesel backup generator for emergency power",
    serialNumber: "GEN-50K-20",
    model: "PowerGen 50K",
    manufacturer: "ElectroPower",
    category: "machinery",
    purchaseDate: "2019-11-05",
    purchasePrice: 35000,
    location: "Facility Exterior",
    department: "Facilities",
    status: "active",
    lastInspection: "2023-04-05",
    nextInspection: "2023-05-05",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=300&h=200",
    notes: "Requires monthly testing",
  },
  {
    id: "4",
    name: "Pallet Jack #P44",
    description: "Manual pallet jack for warehouse operations",
    serialNumber: "PJ-2000-44",
    model: "PalletMaster 2000",
    manufacturer: "LiftWell",
    category: "tools",
    purchaseDate: "2022-02-18",
    purchasePrice: 1500,
    location: "Warehouse A",
    department: "Logistics",
    status: "inactive",
    lastInspection: "2023-03-01",
    nextInspection: "2023-06-01",
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=300&h=200",
    notes: "Hydraulic fluid leak, needs repair",
  },
  {
    id: "5",
    name: "Safety Harness #SH15",
    description: "Fall protection safety harness for working at heights",
    serialNumber: "SH-PRO-15",
    model: "SafetyPro",
    manufacturer: "Heights Protection",
    category: "safety",
    purchaseDate: "2022-06-10",
    purchasePrice: 350,
    location: "Equipment Room",
    department: "Safety",
    status: "retired",
    lastInspection: "2023-04-10",
    nextInspection: null,
    image: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?auto=format&fit=crop&w=300&h=200",
    notes: "Failed inspection, replaced with newer model",
  },
  {
    id: "6",
    name: "Conference Room Projector",
    description: "4K projector for main conference room",
    serialNumber: "PRJ-4K-001",
    model: "UltraView 4K",
    manufacturer: "VisualTech",
    category: "electronics",
    purchaseDate: "2022-01-15",
    purchasePrice: 2800,
    location: "Conference Room A",
    department: "IT",
    status: "active",
    lastInspection: "2023-02-15",
    nextInspection: "2023-08-15",
    image: null,
    notes: null,
  },
];

// Mock Asset Statistics
export const mockStatistics: AssetStatistics = {
  total: 6,
  active: 3,
  maintenance: 1,
  inactive: 1,
  retired: 1,
  inspectionsDue: 2,
  inspectionsOverdue: 1,
};

// Mock Inspections
export const mockInspections: Inspection[] = [
  {
    id: "1",
    assetId: "1",
    assetName: "Forklift #A102",
    inspectionType: "Monthly Safety Check",
    date: "2023-04-15",
    completedBy: "John Doe",
    status: "completed",
    items: [
      {
        id: "item1",
        question: "Are all safety features functional?",
        status: "pass",
        priority: null,
        notes: null,
      },
      {
        id: "item2",
        question: "Is the hydraulic system working properly?",
        status: "pass",
        priority: null,
        notes: null,
      },
      {
        id: "item3",
        question: "Is the horn working?",
        status: "fail",
        priority: "medium",
        notes: "Horn is not loud enough, needs adjustment",
      },
    ],
    notes: "Overall in good condition, horn needs to be fixed",
    photos: ["https://via.placeholder.com/300"],
  },
  {
    id: "2",
    assetId: "2",
    assetName: "Air Compressor #C55",
    inspectionType: "Quarterly Maintenance",
    date: "2023-03-01",
    completedBy: "Jane Smith",
    status: "completed",
    items: [
      {
        id: "item1",
        question: "Oil change completed?",
        status: "pass",
        priority: null,
        notes: null,
      },
      {
        id: "item2",
        question: "Filters replaced?",
        status: "pass",
        priority: null,
        notes: null,
      },
    ],
    notes: "All maintenance tasks completed",
    photos: [],
  },
  {
    id: "3",
    assetId: "3",
    assetName: "Generator #G20",
    inspectionType: "Monthly Operational Test",
    date: "2023-05-10",
    completedBy: "Mike Johnson",
    status: "in-progress",
    items: [
      {
        id: "item1",
        question: "Does generator start properly?",
        status: "fail",
        priority: "high",
        notes: "Generator fails to start consistently",
      },
      {
        id: "item2",
        question: "Is fuel level adequate?",
        status: "pass",
        priority: null,
        notes: null,
      },
    ],
    notes: "Generator starting issues, needs service",
    photos: [],
  },
  {
    id: "4",
    assetId: "4",
    assetName: "Pallet Jack #P44",
    inspectionType: "Annual Inspection",
    date: "2023-05-20",
    completedBy: "Pending",
    status: "pending",
    items: [
      {
        id: "item1",
        question: "Are wheels in good condition?",
        status: "na",
        priority: null,
        notes: null,
      },
      {
        id: "item2",
        question: "Do hydraulics function properly?",
        status: "na",
        priority: null,
        notes: null,
      },
    ],
    notes: null,
    photos: [],
  },
];

// Mock Activity
export const mockActivity: ActivityItem[] = [
  {
    id: "1",
    type: "inspection",
    date: "2023-04-15",
    assetId: "1",
    assetName: "Forklift #A102",
    description: "Completed monthly inspection",
    user: "John Smith",
  },
  {
    id: "2",
    type: "maintenance",
    date: "2023-04-12",
    assetId: "2",
    assetName: "Air Compressor #C55",
    description: "Started maintenance - filter replacement",
    user: "Mike Johnson",
  },
  {
    id: "3",
    type: "status-change",
    date: "2023-04-10",
    assetId: "5",
    assetName: "Safety Harness #SH15",
    description: "Status changed from 'active' to 'retired'",
    user: "Sarah Williams",
  },
];